[versions]
androidGradlePlugin = "7.4.0"
androidxCore = "1.9.0"
androidxLifecycle = "2.5.1"
androidxActivity = "1.6.1"
androidxComposeCompiler = "1.3.2"
androidxHilt = "1.0.0"
androidxNavigation = "2.5.3"
androidxRoom = "2.4.3"
androidxTest = "1.5.0" # https://github.com/android/android-test/issues/1412
androidxTestExt = "1.1.4"
androidxTestRunner = "1.5.1"
nav_version = "2.5.3"
coroutines = "1.6.4"
hilt = "2.44.2"
junit = "4.13.2"
kotlin = "1.7.20"
ksp = "1.7.20-1.0.8"
nav-version = "2.5.3"
retrofitVersion = '2.9.0'
okhttpVersion = '5.0.0-alpha.3'
timberVersion = '5.0.1'
coilVersion  = '2.2.2'
kotlinSerialization="1.4.1"
encryptKey='1.1.0-alpha03'
datastore='1.0.0'
magotp='1.0'
firebase='31.2.0'
gms='4.3.15'
navBar="1.3.1"
lifecycle="2.6.0-alpha01"
accompilist="0.28.0"
[libraries]
androidx-compose-bom="androidx.compose:compose-bom:2022.12.00"
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidxCore" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidxActivity" }
androidx-compose-compiler = { module = "androidx.compose.compiler:compiler", version.ref = "androidxComposeCompiler" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3" }
androidx-compose-ui = { module = "androidx.compose.ui:ui" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
androidx-compose-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }
androidx-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "androidxHilt" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidxLifecycle" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidxLifecycle" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "androidxNavigation" }
androidx-navigation-safeargs ={ module="androidx.navigation:navigation-safe-args-gradle-plugin" , version.ref="nav_version"}
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "androidxRoom" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "androidxRoom" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "androidxRoom" }
androidx-test-core = { module = "androidx.test:core", version.ref = "androidxTest" }
androidx-test-ext-junit = { module = "androidx.test.ext:junit", version.ref = "androidxTestExt" }
androidx-test-runner = { module = "androidx.test:runner", version.ref = "androidxTestRunner" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }
hilt-android-testing = { module = "com.google.dagger:hilt-android-testing", version.ref = "hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }
hilt-gradle-plugin = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "hilt" }
junit = { module = "junit:junit", version.ref = "junit" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
com-squareup-retrofit2={module="com.squareup.retrofit2:retrofit",version.ref="retrofitVersion"}
com-squareup-retrofit2-gson={module="com.squareup.retrofit2:converter-gson",version.ref="retrofitVersion"}
com-squareup-okhttp3-interceptor={module="com.squareup.okhttp3:logging-interceptor",version.ref="okhttpVersion"}
com-jakewharton-timber={module="com.jakewharton.timber:timber",version.ref="timberVersion"}
io-coil-kt-coil={module ="io.coil-kt:coil",version.ref="coilVersion"}
io-coil-kt-coil-compose={module ="io.coil-kt:coil-compose",version.ref="coilVersion"}
kotlin-serialization-json={module="org.jetbrains.kotlinx:kotlinx-serialization-json",version.ref="kotlinSerialization"}
androidx-security={module="androidx.security:security-crypto",version.ref="encryptKey"}
androidx-datastore={module='androidx.datastore:datastore-preferences',version.ref="datastore"}
com-google-firebase={module='com.google.firebase:firebase-bom',version.ref='firebase'}
com-google-firebase-auth-ktx={module='com.google.firebase:firebase-auth-ktx'}
com-google-gms={module='com.google.gms:google-services', version.ref="gms"}
androidx-compose-material={module="androidx.compose.material:material-icons-extended"}
androidx-compose-material-Navbar={module="androidx.compose.material:material",version.ref="navBar"}
com-google-firebase-realtime={module="com.google.firebase:firebase-database-ktx"}
androidx-lifecycle={ module="androidx.lifecycle:lifecycle-runtime-compose",version.ref="lifecycle"}
com-google-accompanist={module="com.google.accompanist:accompanist-systemuicontroller",version.ref="accompilist"}
[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin"}
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp"}
gsm={id="com.google.gms.google-services",version.ref="gms"}
hilt-gradle = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
